In [21]:
import pandas as pd

In [22]:
data = pd.read_csv('datos.csv')

data.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-jun-18,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303,NaN,NaN
1,2018.06.18,18-jun-18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson�McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302,NaN,NaN
2,2018.06.09,09-jun-18,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301,NaN,NaN
3,2018.06.08,08-jun-18,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300,NaN,NaN
4,2018.06.04,04-jun-18,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299,NaN,NaN

In [25]:
data = pd.read_csv('datos.csv')

print(data.head())

  Case Number       Date    Year        Type    Country             Area  \
0  2018.06.25  25-jun-18  2018.0     Boating        USA       California
1  2018.06.18  18-jun-18  2018.0  Unprovoked        USA          Georgia
2  2018.06.09  09-jun-18  2018.0     Invalid        USA           Hawaii
3  2018.06.08  08-jun-18  2018.0  Unprovoked  AUSTRALIA  New South Wales
4  2018.06.04  04-jun-18  2018.0    Provoked     MEXICO           Colima

                         Location     Activity             Name Sex   ...  \
0     Oceanside, San Diego County     Paddling      Julie Wolfe    F  ...
1  St. Simon Island, Glynn County     Standing  Adyson�McNeely     F  ...
2                    Habush, Oahu      Surfing      John Denges    M  ...
3              Arrawarra Headland      Surfing             male    M  ...
4                        La Ticla  Free diving   Gustavo Ramos     M  ...

          Species           Investigator or Source                       pdf  \
0      White shark                R. Collier, GSAF      2018.06.25-Wolfe.pdf
1              NaN  K.McMurray, TrackingSharks.com    2018.06.18-McNeely.pdf
2              NaN  K.McMurray, TrackingSharks.com     2018.06.09-Denges.pdf
3        2 m shark                  B. Myatt, GSAF  2018.06.08-Arrawarra.pdf
4  Tiger shark, 3m                       A .Kipper      2018.06.04-Ramos.pdf

                                        href formula  \
0  http://sharkattackfile.net/spreadsheets/pdf_di...
1  http://sharkattackfile.net/spreadsheets/pdf_di...
2  http://sharkattackfile.net/spreadsheets/pdf_di...
3  http://sharkattackfile.net/spreadsheets/pdf_di...
4  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                href Case Number.1  \
0  http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.25
1  http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.18
2  http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.09
3  http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.08
4  http://sharkattackfile.net/spreadsheets/pdf_di...    2018.06.04

  Case Number.2 original order Unnamed: 22 Unnamed: 23
0    2018.06.25           6303         NaN         NaN
1    2018.06.18           6302         NaN         NaN
2    2018.06.09           6301         NaN         NaN
3    2018.06.08           6300         NaN         NaN
4    2018.06.04           6299         NaN         NaN

[5 rows x 24 columns]

<h1>Toma muestras</h1>

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6302 entries, 0 to 6301
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             6301 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6302 non-null   int64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(1), int64(1), object(22)
memory usage: 1.2+ MB

<h1>Se muestra el tipo de datos que contiene el documento csv</h1>

In [15]:
data.describe()

              Year  original order
count  6300.000000     6302.000000
mean   1927.272381     3152.499683
std     281.116308     1819.375481
min       0.000000        2.000000
25%    1942.000000     1577.250000
50%    1977.000000     3152.500000
75%    2005.000000     4727.750000
max    2018.000000     6303.000000

<h1>Datos estadísticos desviación estandar</h1>

In [14]:
print(data.columns)

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

<h1>Muestra las columnas de la información</h1>

In [16]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shape.html
data.shape

(6302, 24)

<h1>NUMERO DE FILAS Y COLUMNAS</h1>

In [27]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html

data.head(500)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-jun-18,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303,NaN,NaN
1,2018.06.18,18-jun-18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson�McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302,NaN,NaN
2,2018.06.09,09-jun-18,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301,NaN,NaN
3,2018.06.08,08-jun-18,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300,NaN,NaN
4,2018.06.04,04-jun-18,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2014.10.02.b,02-oct-14,2014.0,Unprovoked,USA,California,"Walls Beach, Vandenberg AFB, Santa Barbara County",Surfing,M.M.,M,...,8' to 10' shark,"R. Collier, GSAF",2014.10.02.b-Vandenberg.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.10.02.b,2014.10.02.b,5808,NaN,NaN
496,2014.10.02.a,02-oct-14,2014.0,Unprovoked,AUSTRALIA,Western Australia,"Kelpids Beach, Wylie Bay, Esperance",Surfing,Sean Pollard,M,...,"2 white shark: 13' & 9""8""","9News, 2/15/2015",2014.10.02.a-Pollard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.10.02.a,2014.10.02.a,5807,NaN,NaN
497,2014.09.21,21-sep-14,2014.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Jordan Lefebvre,M,...,NaN,"NBC2 News, 9/21/2014",2014.09.21-Lefebvre.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.09.21,2014.09.21,5806,NaN,NaN
498,2014.09.13.R,Reported 12-Sep-2014,2014.0,Unprovoked,FRENCH POLYNESIA,Moorea,Tiahura Lagoon,Feeding fish,female,F,...,Blacktip shark,"LeDepeche, 9/12/2014",2014.09.12.R-Moorea.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.09.13.R,2014.09.13.R,5805,NaN,NaN
499,2014.09.13,13-sep-14,2014.0,Invalid,USA,California,"Manresa State Beach, Santa Cruz County",Surfing,Beau Browning,M,...,No shark involvement,"R. Collier, GSAF",2014.09.13-Browning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.09.13,2014.09.13,5804,NaN,NaN